---
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.55.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
        files: ^\.github/workflows/
        types: [yaml]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-d relaxed]
